require 'erb'
require 'yaml'
require 'json'

task :clean do
  FileUtils.mkdir_p('target')
  FileUtils.rm_rf(Dir.glob('target/*'))
end

desc "Builds logstash filters"
task :build => :clean do
  puts "===> Building ..."
  compile_erb 'src/logstash-filters/default.conf.erb', 'target/logstash-filters-default.conf'
  compile_erb 'src/logstash-filters/cluster_monitor.conf.erb', 'target/logstash-filters-monitor.conf'

  puts "===> Artifacts:"
  puts `find target`
end

task default: [
  :build
]

def compile_erb(source_file, dest_file)
  if File.extname(source_file) == '.erb'
    output = ERB.new(File.read(source_file)).result(binding)
    File.write(dest_file, output)
  else
    cp source_file, dest_file
  end
end

task :clean_templates do
  FileUtils.mkdir_p('spec/logstash-templates/target')
  FileUtils.rm_rf(Dir.glob('spec/logstash-templates/target/*'))
end

def compile_bosh_template(template_file, config_file, dest_file)

  config = YAML.load(File.read(config_file)).to_json
  `bosh-template #{template_file} --context '#{config}' > #{dest_file}`

end
