##------------------------------
## Parses LogMessage APP events.|
##------------------------------

if [@source][type] =~ /APP(|\/.*)$/ {

    mutate {
      add_tag => [ "logmessage-app" ]
    }

    mutate {
      # Firehose sets values like "APP/PROC/WEB". Rename just to "APP" for simplicity.
      replace => { "[@source][type]" => "APP" }
    }

    # Parse application logs based on msg format.
    # Marks unknown format with [unknown_msg_format] tag.

    ## ---- Format 1: JSON
    if [@message] =~ /^\s*{".*}\s*$/ { # if it looks like JSON

        json {
            source => "@message"
            target => "app"
            id => "cloudfoundry/app-message/json"
        }

        if !("_jsonparsefailure" in [tags]) {

            mutate {
                rename => { "[app][message]" => "@message" } # @message
            }
            # concat message and exception
            if [app][exception] {
                mutate {
                    ## NOTE: keep line break and new line spacing (new line is inserted in logstash in such a way)
                    replace => { "@message" => "%{@message}
%{[app][exception]}" }
                    remove_field => [ "[app][exception]" ]
              }
            }

            mutate {
                rename => { "[app][level]" => "@level" } # @level
            }

        } else {
            ruby {
            id => "cloudfoundry/app-app/json-length"
            code => "
            begin
              max_length = 32000
              msg_value = event.get(
                'app._value'
              )
              if msg_value && msg_value.is_a?(String) && msg_value.length > max_length
                truncated_message = msg_value[0...max_length] + 'cloud.gov log limit reached'
                event.set('app._value',truncated_message)
              end
            rescue => e
             logger.error('ruby erryr ' + e.message )
            end
            "
           }
        json {
        source => "@message"
        target => "app"
        id => "cloudfoundry/app-message/json2"
        }

        if !("_jsonparsefailure" in [tags]) {

            mutate {
                rename => { "[app][message]" => "@message" } # @message
            }

            mutate {
                rename => { "[app][level]" => "@level" } # @level
            }
        }
        else
        {
            mutate {
                add_tag => [ "unknown_msg_format_json" ]
                remove_tag => ["_jsonparsefailure"]
            }

        }
    }

    ## ---- Format 2: "[CONTAINER] .." (Tomcat logs)
    } else if [@message] =~ /^\s*\[CONTAINER\]/ {

        # Tomcat specific parsing (in accordance with https://github.com/cloudfoundry/java-buildpack-support/blob/master/tomcat-logging-support/src/main/java/com/gopivotal/cloudfoundry/tomcat/logging/CloudFoundryFormatter.java)
        grok {
            match => [ "@message", "(?<app_logger>\[CONTAINER\]%{SPACE}%{NOTSPACE})%{SPACE}%{LOGLEVEL:@level}%{SPACE}%{GREEDYDATA:@message}" ]
            overwrite => [ "@message", "@level" ]
            tag_on_failure => [ "unknown_msg_format_tomcat" ]
            id => "cloudfoundry/app-message/tomcat_message/grok"
        }
        mutate {
            rename => { "app_logger" => "[app][logger]" }
        }

    } else {

        mutate {
                add_tag => [ "unknown_msg_format" ]
            }
    }

}
