if [@source][component] == "snort" {
  grok {
    match => {
      "@message" => "\[%{INT:gid}:%{INT:sid}:%{INT:rev}\]\s%{DATA:msg}\s\{%{DATA:proto}\}\s%{IP:src_ip}:%{INT:src_port}\s->\s%{IP:dst_ip}:%{INT:dst_port}"
       tag_on_failure => [ "grok_snort_error" ]
    }
  }
}
if [@source][component] == "clamd" {
  grok {
    match => {
      "@message" => "%{WORD:event_type}:\s%{DATA:file_path}:\s%{DATA:signature_name}\sFOUND"
       tag_on_failure => [ "grok_clamd_error" ]
    }
  }
}

    