require 'erb'
require 'rake'

# Clean tasks
task :clean do
  FileUtils.mkdir_p('target')
  FileUtils.rm_rf(Dir.glob('target/*'))
end

# Build tasks
desc "Builds Logstash filters"
task :build => :clean do
  build_erb 'src/logstash-filters/default.conf.erb', 'target/logstash-filters-default.conf'
  build_erb 'src/logstash-filters/audit_event.conf.erb', 'target/audit_event.conf'
  build_erb 'src/logstash-filters/cloudwatch.conf.erb', 'target/cloudwatch.conf'
  build_erb 'src/logstash-filters/falco.conf.erb', 'target/falco.conf'
  build_erb 'src/logstash-filters/metrics.conf.erb', 'target/metrics.conf'
end

def build_erb(source_erb_file, target_file)
  puts "===> Building ..."
  compile_erb source_erb_file, target_file

  puts "===> Artifacts:"
  puts `find target`
end

task default: [
  :build
]

def unescape_embedded_doublequote(str)
  str.gsub("_eQT_", '\\\\\\\\\"')
end

def unescape_embedded_newline(str)
  str.gsub('_eLF_', '\\\\\\\\n')
end

def compile_erb(source_file, dest_file)
  if File.extname(source_file) == '.erb'
    output = ERB.new(File.read(source_file)).result(binding)
    output = unescape_embedded_doublequote(output)
    output = unescape_embedded_newline(output)
    File.write(dest_file, output)
    puts "ERB #{source_file} -> #{dest_file}"
  else
    cp source_file, dest_file
  end
end
