opensearch*: logs-opensearch
curator.*: logs-opensearch
firehose-to-syslog.*: logs-opensearch
ingestor.*: logs-opensearch
archiver.*: logs-opensearch
parser.*: logs-opensearch
maintenance.*: logs-opensearch
